# Generated by Django 3.2.8 on 2021-10-27 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subject',
            new_name='Course',
        ),
    ]
